name: Broken links

on:
  workflow_dispatch:
  schedule:
    - cron: "23 23 * * 0"

permissions:
  issues: write

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1

      - name: Find already existing issue
        id: find-issue
        run: |
          gh issue list -l "bug" -l "automated" -L 1 -S "in:title Link Checker Report" -s "open" --json "id"
        env:
          GH_TOKEN: ${{ github.token }}
          
      - name: Close issue if everything is fine
        # if: env.lychee_exit_code == 0
        run: echo "Outputs issue_number is ${{ steps.find-issue.outputs.issues }}"

      # - name: Create Issue From File
      #  if: env.lychee_exit_code != 0
      #  uses: peter-evans/create-issue-from-file@v5
      #  with:
      #    title: Link Checker Report
      #    content-filepath: ./lychee/out.md
      #    labels: bug, automated
